### ISSUE TITLE
Convert to a raw Web Component

### ISSUE THREAD

**Issue by warpech** [Juicy/juicy-filedrop#1]
To be able run both in Polymer 0.5 and 1.0, it seems the best approach to downgrade this element to be using raw Web Components APIs and XmlHttpRequest instead of `core-ajax`.

Release the new version as 1.0.0

**Comment by miyconst** [comment]
Same situation as described in this issue: https://github.com/Juicy/juicy-color-picker/issues/1

The `juicy-filedrop` has the following attributes which are bindable right now and won't be after rework: `url`, `customheader`, `value`, `maxfilesize`, `allowedmimetypes`.

**Comment by warpech** [comment]
We agreed to freeze work on this until Images app is updated to Polymer 1.0

**Comment by miyconst** [comment]
`juicy-filedrop` is now a Polymer 1.1 component, should it sill be converted to vanilla?

**Comment by warpech** [comment]
Not needed at the moment. Closing
