### ISSUE TITLE
Improve error message for file size limit

### ISSUE THREAD

**Issue by jwillmer** [Juicy/juicy-filedrop#2]
I added a file size limit of 2 `MB` and if I upload a image over 2 `MB` I get the following error:

`File IMG_20160909_144718.jpg is too big. Maximum file size is: 1953.125kb.`

It would be nice to convert the max file size limit to `MB`. No normal user knows about `kb` and it is hard to read.

**Comment by warpech** [comment]
Fixed in #3, merged
